# Generated by Django 4.0.6 on 2022-12-06 16:39

from django.db import migrations

def create_groups(apps, schema_migration):
    User = apps.get_model('authentication', 'User')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_photo = Permission.objects.get(codename='add_photo')
    change_photo = Permission.objects.get(codename='change_photo')
    delete_photo = Permission.objects.get(codename='delete_photo')
    view_photo = Permission.objects.get(codename='view_photo')
    
    coworker_permissions = [
        add_photo,
        change_photo,
        delete_photo,
        view_photo,
    ]
    coworker = Group(name='coworkers')
    coworker.save()
    coworker.permissions.set(coworker_permissions)

    friend = Group(name='friends')
    friend.save()
    friend.permissions.add(view_photo)

    recruiter = Group(name='recruiters')
    recruiter.save()
    recruiter.permissions.add(view_photo)
    
    for user in User.objects.all():
        if user.role == 'COWORKER':
            coworker.user_set.add(user)
        if user.role == 'FRIEND':
            friend.user_set.add(user)
        if user.role == 'RECRUITER':
            recruiter.user_set.add(user)

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
